### ISSUE TITLE
Because that's what containers are for

### ISSUE THREAD

**Issue by kheide** [sherifadel90/AppDynamicsPoVReadyLab#1]
Please can you just provide this as docker images instead? Would make deploying it 100% hassle-free! :-)

**Comment by sherifadel90** [comment]
He Kheide,
This Repo is intended to be a Lab, and the purpose of the Lab is to do a Monolithic Deployment and step by step Agents Installation to simulate a customer engagement, not to abstract the deployment in this training and abstract the intended knowledge that we want to transfer to the Lab Users. However, thank you for the feedback though :)
